### ISSUE TITLE
Setting the empty string breaks setting

### ISSUE THREAD

**Issue by ptth222** [truocphan/json-duplicate-keys#3]
If you set the empty string using the set method you can longer set anything else.

Code to reproduce:
```
temp = jdks.JSON_DUPLICATE_KEYS({})
temp.set('', "asdf")
temp.set("foo", "bar") #returns False
```

Some preliminary testing looks like switching the order of the if statements in set fixes the issue. I moved the elif that looks for a zero length name_split_first to the second test instead of the third and it lets you set new values again. I can submit a PR if that would help.

**Comment by truocphan** [comment]
I will check and get back to you soon.

**Comment by truocphan** [comment]
Your issue has been fixed (https://github.com/truocphan/json-duplicate-keys/compare/2024.4.20...2024.7.17). Please help me check again if the issue still exists. Thank you

**Comment by ptth222** [comment]
Looks fixed to me! Thanks.
